### ISSUE TITLE
Do not send the first data point right at the boot

### ISSUE THREAD

**Issue by simonerom** [iotexproject/pebble-firmware#20]
I've noticed that the Pebble firmware sends the first data point on every boot, then the 5 minutes interval kicks in. This allows the users to "manipulate" the data point frequency allowing them to send data more frequently than the preset 5-minutes by simply rebooting the device (see image below). Possibly nothing critical, but in theory, this could potentially be an issue for Dapps that rely on the minimum time between 2 data points. The firmware could permanently store the timestamp of the last successfully transmitted data point and start from there at boot time. Alternatively, just send the first data point after [interval] from boot time to disincentivize users.

![image](https://user-images.githubusercontent.com/11096047/146975186-490edaeb-d80b-4bcc-a92f-650852b79809.png)

**Comment by Tide00** [comment]
Fixed in v1.0.6
