### ISSUE TITLE
Rename "App" label on the display 

### ISSUE THREAD

**Issue by simonerom** [iotexproject/pebble-firmware#21]
"App" should be "Firmware" or, in short, "FW", or just nothing: only showing the firmware name + version.

In the future, "App" could generate confusion in the user between the installed firmware and the actual Dapp configuration he has downloaded,

![IMG_2625](https://user-images.githubusercontent.com/11096047/146975733-e8d4339e-d215-4357-b6b7-7e9c5d059bb4.jpg)

**Comment by Tide00** [comment]
Fixed in v1.0.6
